name: CVHJ Scraper

on:
  schedule:
    - cron: "0 12 * * *"    # 14:00 NL tijd
    - cron: "15 21 * * *"   # 23:15 NL tijd
  workflow_dispatch:         # handmatig starten

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # zorgt dat GITHUB_TOKEN gebruikt wordt

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.1"

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("httr2","dplyr","purrr","jsonlite"), repos="https://cloud.r-project.org")'

      - name: Run scraper
        run: |
          Rscript scraper.R

      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/alle_rondes.csv
          git commit -m "Update data [skip ci]" || echo "No changes to commit"
          git push
